/**
 * Refresh the NVIDIA interactivity reference sheets in the main workbook.
 *
 * Inputs are generated by generate_nvidia_gpu_interactivity_reference.py.
 * Spreadsheet authoring intentionally uses @oai/artifact-tool so the existing
 * workbook can be imported, updated in place, rendered, and re-exported.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { FileBlob, SpreadsheetFile } from "@oai/artifact-tool";

const here = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = process.env.LLM_TOKEN_CAPACITY_PROJECT_ROOT
  ? path.resolve(process.env.LLM_TOKEN_CAPACITY_PROJECT_ROOT)
  : path.resolve(here, "..");
const referencePath = path.join(
  projectRoot,
  "docs",
  "dynamic_reasoning_agent_cost",
  "nvidia_gpu_interactivity_reference.json",
);
const workbookPath = path.join(
  projectRoot,
  "outputs",
  "reports",
  "llm_token_capacity_2026_2030.xlsx",
);
const tempPath = `${workbookPath}.tmp.xlsx`;

const reference = JSON.parse(await fs.readFile(referencePath, "utf8"));
const detail = reference.detail;
const summary = reference.summary;
if (detail.length !== 400 || summary.length !== 200) {
  throw new Error(`Unexpected reference shape: detail=${detail.length}, summary=${summary.length}`);
}

const workbook = await SpreadsheetFile.importXlsx(await FileBlob.load(workbookPath));
const navy = "#14213D";
const headerBlue = "#1F4E78";
const paleBlue = "#D9EAF7";
const bandBlue = "#EAF2F8";
const paleYellow = "#FFF2CC";
const paleRed = "#FCE4D6";
const border = "#D9E2EC";
const white = "#FFFFFF";
const dark = "#14213D";

function deleteTables(sheet) {
  for (const table of [...sheet.tables.items]) table.delete();
}

function resetSheet(sheet) {
  deleteTables(sheet);
  sheet.deleteAllDrawings();
  const used = sheet.getUsedRange();
  if (used) {
    try { used.unmerge(); } catch {}
    try { used.conditionalFormats.deleteAll(); } catch {}
    used.clear({ applyTo: "all" });
  }
  sheet.freezePanes.unfreeze();
  sheet.showGridLines = false;
}

function styleTitle(sheet, title, subtitle, lastCol) {
  sheet.getRange(`A1:${lastCol}1`).merge();
  sheet.getRange("A1").values = [[title]];
  sheet.getRange(`A1:${lastCol}1`).format = {
    fill: navy,
    font: { bold: true, color: white, size: 16 },
    verticalAlignment: "center",
  };
  sheet.getRange(`A1:${lastCol}1`).format.rowHeight = 30;

  sheet.getRange(`A2:${lastCol}2`).merge();
  sheet.getRange("A2").values = [[subtitle]];
  sheet.getRange(`A2:${lastCol}2`).format = {
    fill: paleBlue,
    font: { color: dark, size: 10 },
    wrapText: true,
    verticalAlignment: "center",
  };
  sheet.getRange(`A2:${lastCol}2`).format.rowHeight = 34;
}

function styleHeader(range) {
  range.format = {
    fill: headerBlue,
    font: { bold: true, color: white },
    wrapText: true,
    horizontalAlignment: "center",
    verticalAlignment: "center",
    borders: { preset: "all", style: "thin", color: border },
  };
  range.format.rowHeight = 32;
}

function styleBody(sheet, startRow, endRow, endCol) {
  const body = sheet.getRange(`A${startRow}:${endCol}${endRow}`);
  body.format = {
    font: { color: dark, size: 10 },
    verticalAlignment: "center",
    borders: { preset: "all", style: "thin", color: border },
  };
  for (let row = startRow; row <= endRow; row += 1) {
    if ((row - startRow) % 2 === 0) {
      sheet.getRange(`A${row}:${endCol}${row}`).format.fill = bandBlue;
    }
  }
}

function setWidths(sheet, widths, rowCount) {
  widths.forEach((width, index) => {
    sheet.getRangeByIndexes(0, index, rowCount, 1).format.columnWidth = width;
  });
}

// 01b_Interactivity: one auditable row per proxy/GPU/interactivity/workload.
const detailSheet = workbook.worksheets.getItem("01b_Interactivity");
resetSheet(detailSheet);
styleTitle(
  detailSheet,
  "NVIDIA GPU × Interactivity Benchmark Selection",
  "General Chat = single_turn 8K input / 1K output; Agentic = InferenceX agentic_traces. For each 30/50/70/100 tok/s/user target, select the highest output TPS/MW row whose median interactivity meets the target. Framework, concurrency and precision are retained from that selected row.",
  "AA",
);
const detailHeaders = [
  "reference_key", "proxy_model", "source_model", "gpu", "workload", "target_tok_s_user",
  "target_met", "effective_output_tps_per_mw", "selected_tok_s_user", "observed_tok_s_user",
  "bandwidth_power_multiplier_vs_source", "source_gpu", "benchmark_id", "framework", "precision",
  "spec_method", "concurrency", "benchmark_type", "selected_isl", "selected_osl", "candidate_rows",
  "eligible_rows", "selection_status", "source_type", "benchmark_date", "run_url", "method_note",
];
detailSheet.getRange("A4:AA4").values = [detailHeaders];
styleHeader(detailSheet.getRange("A4:AA4"));
const detailRows = detail.map((row) => [
  row.reference_key, row.proxy_model, row.source_model, row.gpu, row.workload, row.target_tok_s_user,
  row.target_met, row.effective_output_tps_per_mw, row.selected_tok_s_user, row.observed_tok_s_user,
  row.performance_multiplier_vs_source, row.source_gpu, row.benchmark_id, row.framework, row.precision,
  row.spec_method, row.concurrency, row.benchmark_type, row.selected_isl, row.selected_osl, row.candidate_rows,
  row.eligible_rows, row.selection_status, row.source_type, row.benchmark_date, row.run_url, row.method_note,
]);
const detailEnd = detailRows.length + 4;
detailSheet.getRangeByIndexes(4, 0, detailRows.length, detailHeaders.length).values = detailRows;
styleBody(detailSheet, 5, detailEnd, "AA");
detailSheet.getRange(`F5:F${detailEnd}`).format.numberFormat = "0";
detailSheet.getRange(`H5:K${detailEnd}`).format.numberFormat = "#,##0.00";
detailSheet.getRange(`M5:M${detailEnd}`).format.numberFormat = "0";
detailSheet.getRange(`Q5:Q${detailEnd}`).format.numberFormat = "#,##0";
detailSheet.getRange(`S5:V${detailEnd}`).format.numberFormat = "#,##0";
detailSheet.getRange(`Y5:Y${detailEnd}`).format.numberFormat = "yyyy-mm-dd";
detailSheet.getRange(`W5:X${detailEnd}`).format.wrapText = true;
detailSheet.getRange(`Z5:AA${detailEnd}`).format.wrapText = true;
for (let index = 0; index < detail.length; index += 1) {
  const rowNumber = index + 5;
  const row = detail[index];
  if (!row.effective_output_tps_per_mw) {
    detailSheet.getRange(`A${rowNumber}:AA${rowNumber}`).format.fill = paleRed;
  } else if (String(row.source_type).includes("scaled") || String(row.source_type).includes("fallback")) {
    detailSheet.getRange(`A${rowNumber}:AA${rowNumber}`).format.fill = paleYellow;
  }
}
detailSheet.tables.add(`A4:AA${detailEnd}`, true, "NvidiaInteractivityDetail");
detailSheet.freezePanes.freezeRows(4);
detailSheet.freezePanes.freezeColumns(4);
setWidths(
  detailSheet,
  [38, 20, 14, 11, 15, 13, 11, 20, 17, 17, 20, 11, 12, 18, 11, 13, 13, 17, 12, 12, 13, 12, 36, 34, 20, 52, 78],
  detailEnd,
);

// 00a_Proxy_TPS_MW: compact formula-linked view of the two workload rows.
const summarySheet = workbook.worksheets.getItem("00a_Proxy_TPS_MW");
resetSheet(summarySheet);
styleTitle(
  summarySheet,
  "NVIDIA GPU × Interactivity × Workload Output TPS/MW",
  "Five proxy models × ten NVIDIA GPU labels × 30/50/70/100 tok/s/user. General Chat uses 8K/1K only; Agentic uses native traces. Cells are linked to 01b_Interactivity so the selected framework, precision and concurrency remain auditable.",
  "N",
);
const summaryHeaders = [
  "proxy_model", "gpu", "interactivity_tok_s_user",
  "general_chat_tps_per_mw", "general_chat_concurrency", "general_chat_precision", "general_chat_framework", "general_chat_source",
  "agentic_tps_per_mw", "agentic_concurrency", "agentic_precision", "agentic_framework", "agentic_source", "method_note",
];
summarySheet.getRange("A4:N4").values = [summaryHeaders];
styleHeader(summarySheet.getRange("A4:N4"));
const detailRowByKey = new Map(detail.map((row, index) => [row.reference_key, index + 5]));
const summaryValues = summary.map((row) => [
  row.proxy_model,
  row.gpu,
  row.interactivity_tok_s_user,
  "", "", "", "", "",
  "", "", "", "", "",
  "Highest output TPS/MW row meeting the InferenceX median-interactivity target; future GPUs use editable HBM-bandwidth/all-in-power scaling only when both inputs are positive.",
]);
const summaryEnd = summaryValues.length + 4;
summarySheet.getRangeByIndexes(4, 0, summaryValues.length, summaryHeaders.length).values = summaryValues;
for (let index = 0; index < summary.length; index += 1) {
  const row = summary[index];
  const outputRow = index + 5;
  const generalDetail = detailRowByKey.get(`${row.proxy_model}|${row.gpu}|general_chat|${row.interactivity_tok_s_user}`);
  const agenticDetail = detailRowByKey.get(`${row.proxy_model}|${row.gpu}|agentic|${row.interactivity_tok_s_user}`);
  if (!generalDetail || !agenticDetail) throw new Error(`Missing detail link for summary row ${outputRow}`);
  summarySheet.getRange(`D${outputRow}:M${outputRow}`).formulas = [[
    `=IF('01b_Interactivity'!H${generalDetail}="","",'01b_Interactivity'!H${generalDetail})`,
    `=IF('01b_Interactivity'!H${generalDetail}="","",'01b_Interactivity'!Q${generalDetail})`,
    `=IF('01b_Interactivity'!H${generalDetail}="","",'01b_Interactivity'!O${generalDetail})`,
    `=IF('01b_Interactivity'!H${generalDetail}="","",'01b_Interactivity'!N${generalDetail})`,
    `='01b_Interactivity'!X${generalDetail}`,
    `=IF('01b_Interactivity'!H${agenticDetail}="","",'01b_Interactivity'!H${agenticDetail})`,
    `=IF('01b_Interactivity'!H${agenticDetail}="","",'01b_Interactivity'!Q${agenticDetail})`,
    `=IF('01b_Interactivity'!H${agenticDetail}="","",'01b_Interactivity'!O${agenticDetail})`,
    `=IF('01b_Interactivity'!H${agenticDetail}="","",'01b_Interactivity'!N${agenticDetail})`,
    `='01b_Interactivity'!X${agenticDetail}`,
  ]];
}
styleBody(summarySheet, 5, summaryEnd, "N");
summarySheet.getRange(`C5:C${summaryEnd}`).format.numberFormat = "0";
summarySheet.getRange(`D5:D${summaryEnd}`).format.numberFormat = "#,##0.00";
summarySheet.getRange(`E5:E${summaryEnd}`).format.numberFormat = "#,##0";
summarySheet.getRange(`I5:I${summaryEnd}`).format.numberFormat = "#,##0.00";
summarySheet.getRange(`J5:J${summaryEnd}`).format.numberFormat = "#,##0";
summarySheet.getRange(`H5:H${summaryEnd}`).format.wrapText = true;
summarySheet.getRange(`M5:N${summaryEnd}`).format.wrapText = true;
styleBody(summarySheet, 5, summaryEnd, "N");
summarySheet.tables.add(`A4:N${summaryEnd}`, true, "NvidiaInteractivitySummary");
summarySheet.freezePanes.freezeRows(4);
summarySheet.freezePanes.freezeColumns(3);
setWidths(summarySheet, [20, 11, 13, 21, 18, 17, 19, 32, 20, 17, 16, 18, 32, 72], summaryEnd);

// Keep the logic sheet aligned with the new two-workload reference taxonomy.
const logicSheet = workbook.worksheets.getItem("00_Logic");
logicSheet.getRange("B3").values = [["NVIDIA 기준 TPS/MW 표는 `00a_Proxy_TPS_MW`, 선택 benchmark 행은 `01b_Interactivity`, R200 이후 HBM bandwidth/all-in power 입력은 `00b_GPU_Scaling`에서 관리합니다."]];
logicSheet.getRange("B6").values = [["gpu_workload_avg_tps_per_mw = general_chat_share*gpu_general_chat_tps + agentic_share*gpu_agentic_tps"]];
logicSheet.getRange("B11").values = [["Interactivity 30/50/70/100마다 InferenceX median_intvty가 목표 이상인 행 중 output TPS/MW 최대 행을 선택합니다. 선택 행의 framework, concurrency, precision을 그대로 유지합니다."]];
logicSheet.getRange("B12").values = [["General Chat은 single_turn 8K/1K, Agentic은 agentic_traces입니다. Short 1K/1K는 표본 부족 때문에 대표 계산에서 제외합니다. Exact workload 전체가 없을 때만 설정된 직전 모델 curve를 fallback으로 표시합니다."]];
logicSheet.getRange("B3:B12").format.wrapText = true;

// Preserve the stable 36-column calculation bridge while collapsing its
// workload math from short+long+agentic to general_chat(8K/1K)+agentic.
// The reserved columns remain in place so downstream INDEX/MATCH ranges do not
// shift and unrelated forecast formulas remain intact.
const benchmarkInput = workbook.worksheets.getItem("01_Benchmark_Input");
const benchmarkValues = benchmarkInput.getRange("A1:AJ10").values;
const isLegacyThreeWorkload = benchmarkValues[0][3] === "short_chat_share";
benchmarkInput.getRange("D1:G1").values = [[
  "general_chat_share", "reserved_share_unused", "agentic_share", "workload_share_sum_check",
]];
benchmarkInput.getRange("H1:L1").values = [[
  "h200_general_chat_tps_per_mw", "h200_reserved_tps_per_mw", "h200_agentic_tps_per_mw", "h200_workload_avg_tps_per_mw", "h200_status",
]];
benchmarkInput.getRange("M1:Q1").values = [[
  "b200_general_chat_tps_per_mw", "b200_reserved_tps_per_mw", "b200_agentic_tps_per_mw", "b200_workload_avg_tps_per_mw", "b200_status",
]];
benchmarkInput.getRange("R1:V1").values = [[
  "gb200_general_chat_tps_per_mw", "gb200_reserved_tps_per_mw", "gb200_agentic_tps_per_mw", "gb200_workload_avg_tps_per_mw", "gb200_status",
]];
benchmarkInput.getRange("W1:AA1").values = [[
  "purpose_general_chat_tps_per_mw", "purpose_reserved_tps_per_mw", "purpose_agentic_tps_per_mw", "purpose_workload_avg_tps_per_mw", "purpose_status",
]];
benchmarkInput.getRange("AG1:AJ1").values = [[
  "general_chat_condition", "reserved_condition", "agentic_condition", "concurrency_interactivity_rule",
]];
for (let rowIndex = 1; rowIndex < benchmarkValues.length; rowIndex += 1) {
  const excelRow = rowIndex + 1;
  const old = benchmarkValues[rowIndex];
  if (isLegacyThreeWorkload) {
    benchmarkInput.getRange(`D${excelRow}:F${excelRow}`).values = [[
      Number(old[3] || 0) + Number(old[4] || 0), 0, Number(old[5] || 0),
    ]];
    benchmarkInput.getRange(`H${excelRow}:J${excelRow}`).values = [[old[8], "", old[9]]];
    benchmarkInput.getRange(`M${excelRow}:O${excelRow}`).values = [[old[13], "", old[14]]];
    benchmarkInput.getRange(`R${excelRow}:T${excelRow}`).values = [[old[18], "", old[19]]];
    benchmarkInput.getRange(`W${excelRow}:Y${excelRow}`).values = [[old[23], "", old[24]]];
  }
  benchmarkInput.getRange(`G${excelRow}`).formulas = [[`=SUM(D${excelRow}:F${excelRow})`]];
  benchmarkInput.getRange(`K${excelRow}`).formulas = [[`=D${excelRow}*H${excelRow}+F${excelRow}*J${excelRow}`]];
  benchmarkInput.getRange(`P${excelRow}`).formulas = [[`=D${excelRow}*M${excelRow}+F${excelRow}*O${excelRow}`]];
  benchmarkInput.getRange(`U${excelRow}`).formulas = [[`=D${excelRow}*R${excelRow}+F${excelRow}*T${excelRow}`]];
  benchmarkInput.getRange(`Z${excelRow}`).formulas = [[`=D${excelRow}*W${excelRow}+F${excelRow}*Y${excelRow}`]];
  benchmarkInput.getRange(`L${excelRow}`).values = [["General Chat uses the 8K/1K reference; Agentic retains the existing agentic reference."]];
  benchmarkInput.getRange(`Q${excelRow}`).values = [["General Chat uses the 8K/1K reference; Agentic retains the existing agentic reference."]];
  benchmarkInput.getRange(`V${excelRow}`).values = [["General Chat uses the 8K/1K reference; Agentic retains the existing agentic reference."]];
  benchmarkInput.getRange(`AA${excelRow}`).values = [["Purpose-built placeholder uses the same two-workload bridge until a comparable benchmark is available."]];
  benchmarkInput.getRange(`AG${excelRow}:AJ${excelRow}`).values = [[
    "General Chat: single_turn ISL/OSL 8192/1024; existing main-config reference.",
    "Reserved column retained only to keep downstream column positions stable; share is 0%.",
    "Agentic: existing trace-derived reference until a matched production benchmark is adopted.",
    "Two-workload calculation: general_chat_share × 8K/1K TPS/MW + agentic_share × agentic TPS/MW.",
  ]];
}
benchmarkInput.getRange("AG2:AJ10").format.wrapText = true;

const calculationSheet = workbook.worksheets.getItem("03_Calculation");
calculationSheet.getRange("V1:X1").values = [["general_chat_share", "reserved_share_unused", "agentic_share"]];
calculationSheet.getRange("AD1:AG1").values = [[
  "power_balance_abs_error", "gpu_share_abs_error", "workload_share_abs_error", "serving_tps_abs_error",
]];
calculationSheet.getRange("AD2:AG2").formulas = [[
  "=ABS(J2-(L2+M2))",
  "=ABS(1-(N2+O2+P2+Q2))",
  "=ABS(1-(V2+W2+X2))",
  "=ABS(AA2-(Y2*Z2))",
]];
calculationSheet.getRange("AD2:AD181").fillDown();
calculationSheet.getRange("AE2:AE181").fillDown();
calculationSheet.getRange("AF2:AF181").fillDown();
calculationSheet.getRange("AG2:AG181").fillDown();
calculationSheet.getRange("AD2:AG181").format.numberFormat = "0.000000";

const checksSheet = workbook.worksheets.getItem("05_Checks");
checksSheet.getRange("B3").formulas = [["=IF(COUNTIF('03_Calculation'!$AD$2:$AD$181,\">0.001\")=0,\"PASS\",\"FAIL\")"]];
checksSheet.getRange("B4").formulas = [["=IF(COUNTIF('03_Calculation'!$AE$2:$AE$181,\">0.002\")=0,\"PASS\",\"FAIL\")"]];
checksSheet.getRange("B6").formulas = [["=IF(COUNTIF('03_Calculation'!$AF$2:$AF$181,\">0.002\")=0,\"PASS\",\"FAIL\")"]];
checksSheet.getRange("B7").formulas = [["=IF(COUNTIF('03_Calculation'!$AG$2:$AG$181,\">0.01\")=0,\"PASS\",\"FAIL\")"]];
checksSheet.getRange("C3").formulas = [["=B3"]];
checksSheet.getRange("C4").formulas = [["=B4"]];
checksSheet.getRange("C6").formulas = [["=B6"]];
checksSheet.getRange("C7").formulas = [["=B7"]];

const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(tempPath);
await fs.rename(tempPath, workbookPath);

console.log(JSON.stringify({
  status: "PASS",
  workbook: workbookPath,
  detail_rows: detail.length,
  summary_rows: summary.length,
  workloads: reference.metadata.workloads,
}, null, 2));
